import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * Result of bulk update visualizations action
 */
export type BulkUpdateVisualizationsResult = {
  /** Total number of content types attempted to update */
  totalAttempted: number;
  /** Number of successfully updated content types */
  succeeded: number;
  /** Number of failed content type updates */
  failed: number;
  /** Array of error messages for failed updates */
  errors: Array<{
    contentTypeId: string;
    contentTypeLabel: string;
    error: string;
  }>;
};

/**
 * Context for generating bulk visualizations report
 */
export type BulkVisualizationsReportContext = {
  /** Result from the bulk update operation */
  result: BulkUpdateVisualizationsResult;
  /** Hub name for the operation */
  hubName: string;
  /** Visualization configuration that was applied */
  visualizationConfig: {
    visualizations: Array<{
      label: string;
      templatedUri: string;
      default?: boolean;
    }>;
  };
  /** Whether this was a dry-run execution */
  isDryRun: boolean;
};

/**
 * Generate markdown report for bulk visualizations update operation
 *
 * @param context - Report generation context
 * @returns Markdown formatted report string
 */
export function generateBulkVisualizationsReport(context: BulkVisualizationsReportContext): string {
  const { result, hubName, visualizationConfig, isDryRun } = context;
  const now = new Date();
  const timestamp = now.toISOString().slice(0, 10);

  let report = `# Bulk Visualizations Update Report\n\n`;
  report += `Generated: ${timestamp}\n\n`;

  // Operation Summary
  report += `## Operation Summary\n\n`;
  report += `- **Hub**: ${hubName}\n`;
  report += `- **Mode**: ${isDryRun ? 'Dry Run (Preview)' : 'Live Execution'}\n\n`;

  // Visualization Configuration
  report += `## Visualization Configuration\n\n`;
  if (visualizationConfig.visualizations.length === 0) {
    report += `No visualizations configured\n\n`;
  } else {
    visualizationConfig.visualizations.forEach(viz => {
      const defaultFlag = viz.default ? ' (default)' : '';
      report += `- **${viz.label}**: \`${viz.templatedUri}\`${defaultFlag}\n`;
    });
    report += `\n`;
  }

  // Results
  report += `## Results\n\n`;
  report += `- **Total Attempted**: ${result.totalAttempted}\n`;
  report += `- **✅ Successful**: ${result.succeeded}\n`;
  report += `- **❌ Failed**: ${result.failed}\n`;

  const successRate =
    result.totalAttempted > 0 ? Math.round((result.succeeded / result.totalAttempted) * 100) : 0;
  report += `- **Success Rate**: ${successRate}%\n\n`;

  // Errors
  if (result.errors.length > 0) {
    report += `## Errors\n\n`;
    for (const error of result.errors) {
      report += `### ${error.contentTypeLabel} (${error.contentTypeId})\n\n`;
      report += `${error.error}\n\n`;
    }
  }

  // Footer
  report += `---\n\n`;
  report += `*This report was automatically generated by the Amplience CMS Tools*\n`;

  return report;
}

/**
 * Save bulk visualizations report to reports folder with timestamp
 *
 * @param report - Report content to save
 * @returns Promise resolving to the path to the saved file
 */
export async function saveBulkVisualizationsReport(report: string): Promise<string> {
  // Create reports directory if it doesn't exist
  const reportsDir = path.join(process.cwd(), 'reports');
  await fs.mkdir(reportsDir, { recursive: true });

  // Generate filename with timestamp
  const now = new Date();
  const timestamp = now.toISOString().slice(0, 19).replace(/T/, '-').replace(/:/g, '-');
  const filename = `bulk-visualizations-${timestamp}.md`;
  const filePath = path.join(reportsDir, filename);

  // Write report to file
  await fs.writeFile(filePath, report, 'utf-8');

  return filePath;
}
