import * as fs from 'fs/promises';
import * as path from 'path';
import type {
  PreparedContentTypeSync,
  PreparedContentTypeSyncResult,
} from '~/commands/sync-content-types';

export type ContentTypeSyncReportContext = {
  prepared: PreparedContentTypeSync;
  result: PreparedContentTypeSyncResult;
};

export function generateContentTypeSyncReport(context: ContentTypeSyncReportContext): string {
  const { prepared, result } = context;
  const lines: string[] = [
    '# Sync Content Types Report',
    '',
    `Generated: ${new Date().toISOString()}`,
    '',
    '## Operation Summary',
    '',
    `- **Source Hub**: ${prepared.sourceHub.name}`,
    `- **Target Hub**: ${prepared.targetHub.name}`,
    `- **Mode**: ${prepared.isDryRun ? 'Dry Run (Preview)' : 'Live Execution'}`,
    `- **Repository Mode**: ${prepared.alignmentPlan.repositoryMode}`,
    `- **Copy Schemas**: ${prepared.copySchemas ? 'Yes' : 'No'}`,
    `- **Synchronize Properties**: ${prepared.syncProperties ? 'Yes' : 'No'}`,
    `- **Overall Result**: ${result.success ? 'Succeeded' : 'Failed or Partial'}`,
    '',
    '## Content Type Plan',
    '',
  ];

  if (prepared.alignmentPlan.items.length === 0) {
    lines.push('No content types selected.', '');
  } else {
    for (const item of prepared.alignmentPlan.items) {
      lines.push(`### ${item.source.settings?.label || item.contentTypeUri}`, '');
      lines.push(`- Schema: ${item.contentTypeUri}`);
      lines.push(`- Actions: ${item.actions.join(', ')}`);
      if (item.settingsChanges.length > 0) {
        lines.push('- Settings Changes:');
        for (const change of item.settingsChanges) {
          lines.push(`  - ${change.setting}`);
          lines.push(
            `    - Current target (${prepared.targetHub.name}): ${formatSettingValue(change.currentTargetValue)}`
          );
          const plannedLabel =
            change.setting === 'visualizations'
              ? `Planned target (from ${prepared.sourceHub.name}, visualization origin adapted for ${prepared.targetHub.name})`
              : `Planned target (from ${prepared.sourceHub.name})`;
          lines.push(`    - ${plannedLabel}: ${formatSettingValue(change.plannedTargetValue)}`);
        }
      }
      lines.push('- Repository Assignments:');
      lines.push(
        `  - Current target (${prepared.targetHub.name}): ${formatRepositoryList(item.target?.repositories)}`
      );
      lines.push(
        `  - Planned target (${prepared.alignmentPlan.repositoryMode}): ${formatRepositoryList(item.desiredRepositories)}`
      );
      if (item.repositoriesToAssign.length > 0) {
        lines.push(`  - Assign: ${item.repositoriesToAssign.join(', ')}`);
      }
      if (item.repositoriesToUnassign.length > 0) {
        lines.push(`  - Unassign: ${item.repositoriesToUnassign.join(', ')}`);
      }
      if (item.repositoriesToAssign.length === 0 && item.repositoriesToUnassign.length === 0) {
        lines.push('  - Changes: none');
      }
      lines.push('');
    }
  }

  lines.push('## Alignment Result', '');
  if (!result.alignment) {
    lines.push('Alignment was not executed.', '');
  } else {
    lines.push(`- Processed: ${result.alignment.processedContentTypes.length}`);
    lines.push(`- Failed: ${result.alignment.failedContentTypes.length}`, '');
    if (result.alignment.commandError) {
      lines.push(`- dc-cli Import Error: ${result.alignment.commandError}`, '');
    }
    for (const failure of result.alignment.failedContentTypes) {
      lines.push(`- ${failure.contentTypeUri}: ${failure.error}`);
    }
    if (result.alignment.failedContentTypes.length > 0) {
      lines.push('');
    }
  }

  lines.push('## Schema Property Synchronization', '');
  lines.push(`- **Property Sync Status**: ${result.propertySyncStatus}`);
  lines.push(`- Processed: ${result.propertySync?.processedContentTypes.length ?? 0}`);
  lines.push(`- Failed: ${result.propertySync?.failedContentTypes.length ?? 0}`, '');
  for (const failure of result.propertySync?.failedContentTypes ?? []) {
    lines.push(`- ${failure.contentTypeId}: ${failure.error}`);
  }

  lines.push('', '---', '', 'Generated by Amplience CMS Tools.', '');

  return lines.join('\n');
}

function formatSettingValue(value: unknown): string {
  if (value === undefined) {
    return '(not set)';
  }

  return JSON.stringify(value);
}

function formatRepositoryList(repositories: string[] | undefined): string {
  if (!repositories || repositories.length === 0) {
    return 'None';
  }

  return [...repositories].sort((left, right) => left.localeCompare(right)).join(', ');
}

export async function saveContentTypeSyncReport(report: string): Promise<string> {
  const reportsDirectory = path.join(process.cwd(), 'reports');
  await fs.mkdir(reportsDirectory, { recursive: true });
  const timestamp = new Date().toISOString().slice(0, 19).replace(/T/, '-').replace(/:/g, '-');
  const reportPath = path.join(reportsDirectory, `sync-content-types-${timestamp}.md`);
  await fs.writeFile(reportPath, report, 'utf-8');

  return reportPath;
}
